// pages/SendSMS.jsx
import React, { useState } from "react";
import jsPDF from "jspdf";

const SendSMS = ({ students = [], studentFees = [] }) => {
  const [selectedStudents, setSelectedStudents] = useState([]);
  const [searchTerm, setSearchTerm] = useState("");
  const [pdfViewerVisible, setPdfViewerVisible] = useState(false);
  const [currentStudent, setCurrentStudent] = useState(null);

  // PDF جنریشن کا فنکشن - CODE HUB ہیڈنگ کے ساتھ
  const createFeeSlipPDF = (student) => {
    const due = (student.totalFee || 0) - (student.feePaid || 0);
    const doc = new jsPDF();
    
    // **CODE HUB ہیڈنگ**
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(59, 130, 246); // نیلا رنگ
    doc.text("CODE HUB", 105, 20, { align: "center" });
    
    doc.setFontSize(16);
    doc.setTextColor(30, 41, 59); // گہرا رنگ
    doc.text("FEE PAYMENT SLIP", 105, 35, { align: "center" });
    
    // لکیر
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 42, 190, 42);
    
    // تاریخ اور تفصیلات
    doc.setFontSize(11);
    doc.setTextColor(100, 116, 139);
    doc.setFont("helvetica", "normal");
    doc.text(`Date: ${new Date().toLocaleDateString('en-PK')}`, 20, 52);
    doc.text(`Receipt No: ${student.studentId || 'N/A'}`, 20, 59);
    
    // طالب علم کی معلومات
    doc.setFontSize(12);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("STUDENT DETAILS:", 20, 75);
    
    doc.setFont("helvetica", "normal");
    doc.text(`Name: ${student.name}`, 25, 85);
    doc.text(`Student ID: ${student.studentId || 'N/A'}`, 25, 93);
    doc.text(`Course: ${student.course || 'N/A'}`, 25, 101);
    
    // فیس کی تفصیلات
    doc.setFont("helvetica", "bold");
    doc.text("FEE DETAILS:", 20, 120);
    
    // ٹیبل
    const startY = 130;
    doc.setFont("helvetica", "bold");
    doc.text("Description", 25, startY);
    doc.text("Amount (Rs.)", 150, startY);
    
    doc.setLineWidth(0.3);
    doc.line(25, startY + 2, 185, startY + 2);
    
    doc.setFont("helvetica", "normal");
    let y = startY + 10;
    
    doc.text("Total Fee", 25, y);
    doc.text(`${student.totalFee || 0}`, 150, y);
    y += 8;
    
    doc.text("Paid Amount", 25, y);
    doc.text(`${student.feePaid || 0}`, 150, y);
    y += 8;
    
    doc.setFont("helvetica", "bold");
    doc.text("Due Amount", 25, y);
    doc.text(`${due}`, 150, y);
    y += 12;
    
    // کل لکیر
    doc.setLineWidth(0.5);
    doc.line(25, y - 8, 185, y - 8);
    
    // آپ کا مطلوبہ پیغام
    doc.setFontSize(13);
    doc.setTextColor(30, 30, 30);
    doc.setFont("helvetica", "normal");
    
    y += 5;
    doc.text(`Dear ${student.name},`, 25, y);
    y += 8;
    doc.text("Your fee details:", 25, y);
    y += 8;
    doc.text(`Total: Rs. ${student.totalFee || 0}`, 25, y);
    y += 8;
    doc.text(`Paid: Rs. ${student.feePaid || 0}`, 25, y);
    y += 8;
    doc.text(`Due: Rs. ${due}`, 25, y);
    y += 8;
    doc.text("Please pay the due amount.", 25, y);
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("CODE HUB Administration", 25, y);
    
    // ادائیگی کی حیثیت
    y += 15;
    doc.setFontSize(12);
    doc.text("Payment Status:", 25, y);
    
    if (due === 0) {
      doc.setTextColor(34, 197, 94); // سبز
      doc.text("PAID", 60, y);
    } else {
      doc.setTextColor(239, 68, 68); // سرخ
      doc.text("PENDING", 60, y);
    }
    
    // فوٹر
    doc.setFontSize(9);
    doc.setTextColor(148, 163, 184);
    doc.setFont("helvetica", "normal");
    doc.text("Generated by CODE HUB Management System", 105, 280, { align: "center" });
    
    return doc;
  };

  // PDF ویوو دکھانے کا فنکشن - اسی صفحے پر
  const showPDFViewer = (student) => {
    setCurrentStudent(student);
    setPdfViewerVisible(true);
    
    // PDF ویوو سیکشن پر سکرول کریں
    setTimeout(() => {
      const pdfViewer = document.getElementById('pdf-viewer-container');
      if (pdfViewer) {
        pdfViewer.scrollIntoView({ behavior: 'smooth' });
      }
    }, 100);
  };

  // PDF ویوو کلوز کریں
  const closePDFViewer = () => {
    setPdfViewerVisible(false);
    setCurrentStudent(null);
  };

  // PDF ڈاؤنلوڈ کرنے کا فنکشن
  const downloadPDF = () => {
    if (!currentStudent) return;
    
    const doc = createFeeSlipPDF(currentStudent);
    const fileName = `CODE_HUB_Fee_Slip_${currentStudent.name.replace(/\s+/g, '_')}.pdf`;
    doc.save(fileName);
    
    setTimeout(() => {
      window.alert(`✅ CODE HUB Fee Slip Downloaded!\n\nFile: ${fileName}\nLocation: Downloads folder`);
    }, 500);
  };

  // WhatsApp پر PDF بھیجنے کا فنکشن
  const sendPDFOnWhatsApp = () => {
    if (!currentStudent) return;
    
    if (!currentStudent.phone) {
      window.alert("📵 Student phone number is missing!");
      return;
    }

    // PDF بنائیں
    const doc = createFeeSlipPDF(currentStudent);
    const fileName = `CODE_HUB_Fee_Slip_${currentStudent.name.replace(/\s+/g, '_')}.pdf`;
    
    // PDF ڈاؤنلوڈ کریں
    doc.save(fileName);
    
    // ہدایات دیں
    setTimeout(() => {
      const phone = currentStudent.phone.replace(/\D/g, '');
      let formattedPhone = phone;
      
      if (phone.length === 10) {
        formattedPhone = "92" + phone.substring(1);
      } else if (phone.length === 11 && phone.startsWith("0")) {
        formattedPhone = "92" + phone.substring(1);
      } else if (phone.startsWith("+92")) {
        formattedPhone = phone.substring(1);
      }
      
      const instructions = `✅ CODE HUB Fee Slip Downloaded!\n\n📄 File: ${fileName}\n📁 Location: Downloads Folder\n\n📱 How to Send on WhatsApp:\n\n1. Open WhatsApp Desktop/Web\n2. Find student: ${currentStudent.phone}\n3. Click 📎 (attachment)\n4. Select "Document"\n5. Choose "${fileName}"\n6. Click SEND\n\n✅ PDF contains:\nDear ${currentStudent.name},\nYour fee details:\nTotal: Rs. ${currentStudent.totalFee || 0}\nPaid: Rs. ${currentStudent.feePaid || 0}\nDue: Rs. ${(currentStudent.totalFee || 0) - (currentStudent.feePaid || 0)}\nPlease pay the due amount.\nCODE HUB Administration`;
      
      window.alert(instructions);
      
      // WhatsApp لنک
      if (window.confirm("Open WhatsApp Web to send the fee slip?")) {
        window.open(`https://web.whatsapp.com/send?phone=${formattedPhone}`, '_blank');
      }
      
    }, 1000);
  };

  // صرف WhatsApp ٹیکسٹ بھیجیں
  const sendWhatsAppText = () => {
    if (!currentStudent) return;
    
    if (!currentStudent.phone) {
      window.alert("📵 Student phone number is missing!");
      return;
    }

    const due = (currentStudent.totalFee || 0) - (currentStudent.feePaid || 0);
    const phone = currentStudent.phone.replace(/\D/g, '');
    let formattedPhone = phone;
    
    if (phone.length === 10) {
      formattedPhone = "92" + phone.substring(1);
    } else if (phone.length === 11 && phone.startsWith("0")) {
      formattedPhone = "92" + phone.substring(1);
    }
    
    // ٹیکسٹ پیغام - CODE HUB کے ساتھ
    const message = `CODE HUB Fee Payment Slip\n\nDear ${currentStudent.name},\n\nYour fee details:\nTotal: Rs. ${currentStudent.totalFee || 0}\nPaid: Rs. ${currentStudent.feePaid || 0}\nDue: Rs. ${due}\n\nPlease pay the due amount.\n\nCODE HUB Administration`;
    
    const whatsappUrl = `https://wa.me/${formattedPhone}?text=${encodeURIComponent(message)}`;
    window.open(whatsappUrl, '_blank');
  };

  // باقی فنکشنز
  const handleSelect = (studentId) => {
    setSelectedStudents(prev =>
      prev.includes(studentId)
        ? prev.filter(id => id !== studentId)
        : [...prev, studentId]
    );
  };

  const handleSelectAll = () => {
    if (selectedStudents.length === students.length) {
      setSelectedStudents([]);
    } else {
      setSelectedStudents(students.map(s => s.studentId));
    }
  };

  const filteredStudents = students.filter(student =>
    student.name?.toLowerCase().includes(searchTerm.toLowerCase()) ||
    student.studentId?.toLowerCase().includes(searchTerm.toLowerCase())
  );

  // بڑی تعداد میں PDFs بھیجیں
  const sendBulkPDFs = () => {
    if (selectedStudents.length === 0) {
      window.alert("⚠️ Please select students first");
      return;
    }

    if (!window.confirm(`Generate CODE HUB fee slips for ${selectedStudents.length} students?`)) return;

    selectedStudents.forEach((studentId, index) => {
      setTimeout(() => {
        const student = students.find(s => s.studentId === studentId);
        if (student) {
          const doc = createFeeSlipPDF(student);
          const fileName = `CODE_HUB_Fee_Slip_${student.name.replace(/\s+/g, '_')}.pdf`;
          doc.save(fileName);
        }
      }, index * 2000);
    });
  };

  // بڑی تعداد میں WhatsApp ٹیکسٹ بھیجیں
  const sendBulkWhatsAppText = () => {
    if (selectedStudents.length === 0) {
      window.alert("⚠️ Please select students first");
      return;
    }

    if (!window.confirm(`Send WhatsApp messages to ${selectedStudents.length} students?`)) return;

    selectedStudents.forEach((studentId, index) => {
      setTimeout(() => {
        const student = students.find(s => s.studentId === studentId);
        if (student) {
          const due = (student.totalFee || 0) - (student.feePaid || 0);
          const phone = student.phone.replace(/\D/g, '');
          let formattedPhone = phone;
          
          if (phone.length === 10) {
            formattedPhone = "92" + phone.substring(1);
          } else if (phone.length === 11 && phone.startsWith("0")) {
            formattedPhone = "92" + phone.substring(1);
          }
          
          const message = `CODE HUB Fee Payment Slip\n\nDear ${student.name},\n\nYour fee details:\nTotal: Rs. ${student.totalFee || 0}\nPaid: Rs. ${student.feePaid || 0}\nDue: Rs. ${due}\n\nPlease pay the due amount.\n\nCODE HUB Administration`;
          
          const whatsappUrl = `https://wa.me/${formattedPhone}?text=${encodeURIComponent(message)}`;
          window.open(whatsappUrl, '_blank');
        }
      }, index * 3000);
    });
  };

  // بڑی تعداد میں PDFs ڈاؤنلوڈ کریں
  const downloadBulkPDFs = () => {
    if (selectedStudents.length === 0) {
      window.alert("⚠️ Please select students first");
      return;
    }

    if (!window.confirm(`Download ${selectedStudents.length} CODE HUB fee slips?`)) return;

    selectedStudents.forEach((studentId, index) => {
      setTimeout(() => {
        const student = students.find(s => s.studentId === studentId);
        if (student) {
          const doc = createFeeSlipPDF(student);
          const fileName = `CODE_HUB_Fee_Slip_${student.name.replace(/\s+/g, '_')}.pdf`;
          doc.save(fileName);
        }
      }, index * 1000);
    });
  };

  // PDF ویوو رینڈر کرنے کا فنکشن
  const renderPDFViewer = () => {
    if (!currentStudent) return null;
    
    const due = (currentStudent.totalFee || 0) - (currentStudent.feePaid || 0);
    
    return (
      <div id="pdf-viewer-container" style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0, 0, 0, 0.8)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1000,
        padding: "20px"
      }}>
        <div style={{
          background: "white",
          borderRadius: "12px",
          width: "90%",
          maxWidth: "900px",
          maxHeight: "90vh",
          overflow: "auto",
          boxShadow: "0 20px 60px rgba(0, 0, 0, 0.3)"
        }}>
          {/* PDF ویوو ہیڈر */}
          <div style={{
            background: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
            color: "white",
            padding: "20px",
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            position: "sticky",
            top: 0,
            zIndex: 10
          }}>
            <div>
              <h3 style={{ margin: 0, fontSize: "20px", display: "flex", alignItems: "center", gap: "10px" }}>
                📄 CODE HUB Fee Slip - {currentStudent.name}
              </h3>
              <p style={{ margin: "5px 0 0 0", opacity: 0.9, fontSize: "14px" }}>
                Student ID: {currentStudent.studentId || 'N/A'}
              </p>
            </div>
            <button
              onClick={closePDFViewer}
              style={{
                background: "rgba(255, 255, 255, 0.2)",
                color: "white",
                border: "none",
                width: "40px",
                height: "40px",
                borderRadius: "50%",
                cursor: "pointer",
                fontSize: "20px",
                display: "flex",
                alignItems: "center",
                justifyContent: "center"
              }}
            >
              ✕
            </button>
          </div>

          {/* PDF کا مواد */}
          <div style={{
            padding: "40px",
            fontFamily: "'Times New Roman', serif",
            background: "white",
            minHeight: "500px"
          }}>
            {/* CODE HUB ہیڈنگ */}
            <div style={{
              textAlign: "center",
              marginBottom: "30px",
              paddingBottom: "15px",
              borderBottom: "2px solid #4f46e5"
            }}>
              <h1 style={{
                fontSize: "32px",
                color: "#3b82f6",
                fontWeight: "bold",
                margin: "0 0 5px 0",
                fontFamily: "'Arial Black', sans-serif"
              }}>
                CODE HUB
              </h1>
              <h2 style={{
                fontSize: "22px",
                color: "#1e293b",
                fontWeight: "bold",
                margin: "0",
                fontFamily: "'Arial', sans-serif"
              }}>
                FEE PAYMENT SLIP
              </h2>
            </div>

            {/* تاریخ اور رسیٹ نمبر */}
            <div style={{
              display: "flex",
              justifyContent: "space-between",
              marginBottom: "30px",
              fontSize: "14px",
              color: "#64748b"
            }}>
              <div>
                <strong>Date:</strong> {new Date().toLocaleDateString('en-PK')}
              </div>
              <div>
                <strong>Receipt No:</strong> {currentStudent.studentId || 'N/A'}
              </div>
            </div>

            {/* طالب علم کی معلومات */}
            <div style={{ marginBottom: "30px" }}>
              <h3 style={{
                fontSize: "16px",
                color: "#1e293b",
                fontWeight: "bold",
                margin: "0 0 15px 0",
                paddingBottom: "5px",
                borderBottom: "1px solid #e2e8f0"
              }}>
                STUDENT DETAILS:
              </h3>
              <div style={{ lineHeight: "2", fontSize: "14px", color: "#334155" }}>
                <div><strong>Name:</strong> {currentStudent.name}</div>
                <div><strong>Student ID:</strong> {currentStudent.studentId || 'N/A'}</div>
                <div><strong>Course:</strong> {currentStudent.course || 'N/A'}</div>
              </div>
            </div>

            {/* فیس کی تفصیلات */}
            <div style={{ marginBottom: "30px" }}>
              <h3 style={{
                fontSize: "16px",
                color: "#1e293b",
                fontWeight: "bold",
                margin: "0 0 15px 0",
                paddingBottom: "5px",
                borderBottom: "1px solid #e2e8f0"
              }}>
                FEE DETAILS:
              </h3>
              
              {/* ٹیبل */}
              <div style={{
                border: "1px solid #d1d5db",
                borderRadius: "6px",
                overflow: "hidden"
              }}>
                <div style={{
                  display: "flex",
                  background: "#f8fafc",
                  padding: "12px 15px",
                  fontWeight: "bold",
                  borderBottom: "1px solid #d1d5db"
                }}>
                  <div style={{ flex: "1" }}>Description</div>
                  <div style={{ width: "150px", textAlign: "right" }}>Amount (Rs.)</div>
                </div>
                
                <div style={{
                  display: "flex",
                  padding: "12px 15px",
                  borderBottom: "1px solid #e5e7eb"
                }}>
                  <div style={{ flex: "1" }}>Total Fee</div>
                  <div style={{ width: "150px", textAlign: "right" }}>{currentStudent.totalFee || 0}</div>
                </div>
                
                <div style={{
                  display: "flex",
                  padding: "12px 15px",
                  borderBottom: "1px solid #e5e7eb"
                }}>
                  <div style={{ flex: "1" }}>Paid Amount</div>
                  <div style={{ width: "150px", textAlign: "right" }}>{currentStudent.feePaid || 0}</div>
                </div>
                
                <div style={{
                  display: "flex",
                  padding: "12px 15px",
                  background: "#f0f9ff",
                  fontWeight: "bold"
                }}>
                  <div style={{ flex: "1" }}>Due Amount</div>
                  <div style={{ width: "150px", textAlign: "right", color: due === 0 ? "#10b981" : "#ef4444" }}>
                    {due}
                  </div>
                </div>
              </div>
            </div>

            {/* پیغام */}
            <div style={{
              marginBottom: "30px",
              padding: "20px",
              background: "#f8fafc",
              borderRadius: "6px",
              borderLeft: "4px solid #4f46e5",
              fontSize: "15px",
              color: "#334155"
            }}>
              <div style={{ marginBottom: "10px" }}>
                <strong>Dear {currentStudent.name},</strong>
              </div>
              <div style={{ marginBottom: "10px" }}>Your fee details:</div>
              <div style={{ marginLeft: "20px", lineHeight: "1.8" }}>
                <div><strong>Total:</strong> Rs. {currentStudent.totalFee || 0}</div>
                <div><strong>Paid:</strong> Rs. {currentStudent.feePaid || 0}</div>
                <div><strong>Due:</strong> Rs. {due}</div>
              </div>
              <div style={{ marginTop: "15px", fontWeight: "bold" }}>
                Please pay the due amount.
              </div>
              <div style={{ marginTop: "20px", textAlign: "right", fontStyle: "italic", color: "#475569" }}>
                CODE HUB Administration
              </div>
            </div>

            {/* ادائیگی کی حیثیت */}
            <div style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: "20px",
              paddingTop: "15px",
              borderTop: "1px solid #e5e7eb"
            }}>
              <div style={{ fontSize: "15px", fontWeight: "bold", color: "#334155" }}>
                Payment Status:
              </div>
              <div style={{
                fontSize: "15px",
                fontWeight: "bold",
                color: due === 0 ? "#10b981" : "#ef4444",
                padding: "5px 15px",
                borderRadius: "20px",
                background: due === 0 ? "#dcfce7" : "#fee2e2"
              }}>
                {due === 0 ? "✓ PAID" : "✗ PENDING"}
              </div>
            </div>

            {/* فوٹر */}
            <div style={{
              textAlign: "center",
              fontSize: "11px",
              color: "#94a3b8",
              marginTop: "30px",
              paddingTop: "10px",
              borderTop: "1px solid #e2e8f0",
              fontFamily: "'Arial', sans-serif"
            }}>
              Generated by CODE HUB Management System
            </div>
          </div>

          {/* ایکشن بٹنز */}
          <div style={{
            padding: "20px",
            background: "#f8fafc",
            borderTop: "1px solid #e2e8f0",
            display: "flex",
            gap: "15px",
            justifyContent: "center",
            flexWrap: "wrap",
            position: "sticky",
            bottom: 0
          }}>
            <button
              onClick={downloadPDF}
              style={{
                padding: "12px 24px",
                background: "#10b981",
                color: "white",
                border: "none",
                borderRadius: "8px",
                cursor: "pointer",
                fontWeight: "600",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                fontSize: "15px",
                minWidth: "180px"
              }}
            >
              ⬇️ Download PDF
            </button>
            
            <button
              onClick={sendPDFOnWhatsApp}
              disabled={!currentStudent.phone}
              style={{
                padding: "12px 24px",
                background: currentStudent.phone ? "#4f46e5" : "#cbd5e1",
                color: "white",
                border: "none",
                borderRadius: "8px",
                cursor: currentStudent.phone ? "pointer" : "not-allowed",
                fontWeight: "600",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                fontSize: "15px",
                minWidth: "180px"
              }}
            >
              📱 Send via WhatsApp
            </button>
            
            <button
              onClick={sendWhatsAppText}
              disabled={!currentStudent.phone}
              style={{
                padding: "12px 24px",
                background: currentStudent.phone ? "#8b5cf6" : "#cbd5e1",
                color: "white",
                border: "none",
                borderRadius: "8px",
                cursor: currentStudent.phone ? "pointer" : "not-allowed",
                fontWeight: "600",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                fontSize: "15px",
                minWidth: "180px"
              }}
            >
              💬 Send Text Only
            </button>
          </div>
        </div>
      </div>
    );
  };

  return (
    <div style={{
      padding: "20px",
      maxWidth: "1200px",
      margin: "0 auto",
      background: "#f8fafc",
      minHeight: "100vh",
      fontFamily: "'Segoe UI', 'Roboto', sans-serif"
    }}>
      
      {/* Header */}
      <div style={{
        background: "linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%)",
        borderRadius: "12px",
        padding: "25px",
        marginBottom: "25px",
        textAlign: "center",
        color: "white",
        boxShadow: "0 4px 20px rgba(79, 70, 229, 0.2)"
      }}>
        <h1 style={{ margin: "0 0 10px 0", fontSize: "28px", fontWeight: "700" }}>🏫 CODE HUB Fee Slip System</h1>
        <p style={{ margin: "0", fontSize: "16px", opacity: 0.9 }}>Generate and send professional CODE HUB fee slips</p>
      </div>

      {/* Instructions */}
      <div style={{
        background: "white",
        borderRadius: "12px",
        padding: "20px",
        marginBottom: "20px",
        boxShadow: "0 2px 10px rgba(0,0,0,0.08)"
      }}>
        <h3 style={{ margin: "0 0 15px 0", color: "#1e293b", display: "flex", alignItems: "center", gap: "10px" }}>
          📋 How to Send CODE HUB Fee Slip
        </h3>
        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(250px, 1fr))", gap: "15px" }}>
          <div style={{ background: "#f1f5f9", padding: "15px", borderRadius: "8px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
              <div style={{ background: "#4f46e5", color: "white", width: "24px", height: "24px", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold" }}>1</div>
              <strong>Click "📄 PDF" Button</strong>
            </div>
            <p style={{ margin: "0", color: "#475569", fontSize: "14px" }}>Fee slip will open in viewer on same page</p>
          </div>
          
          <div style={{ background: "#f1f5f9", padding: "15px", borderRadius: "8px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
              <div style={{ background: "#4f46e5", color: "white", width: "24px", height: "24px", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold" }}>2</div>
              <strong>Review the Slip</strong>
            </div>
            <p style={{ margin: "0", color: "#475569", fontSize: "14px" }}>Check all details in the PDF-like view</p>
          </div>
          
          <div style={{ background: "#f1f5f9", padding: "15px", borderRadius: "8px" }}>
            <div style={{ display: "flex", alignItems: "center", gap: "10px", marginBottom: "10px" }}>
              <div style={{ background: "#4f46e5", color: "white", width: "24px", height: "24px", borderRadius: "50%", display: "flex", alignItems: "center", justifyContent: "center", fontWeight: "bold" }}>3</div>
              <strong>Download or Send</strong>
            </div>
            <p style={{ margin: "0", color: "#475569", fontSize: "14px" }}>Use buttons in viewer to download or send</p>
          </div>
        </div>
      </div>

      {/* PDF ویوو */}
      {pdfViewerVisible && renderPDFViewer()}

      {/* Main Content */}
      <div style={{
        background: "white",
        borderRadius: "12px",
        padding: "25px",
        boxShadow: "0 2px 10px rgba(0,0,0,0.08)"
      }}>
        
        {/* Search Bar */}
        <div style={{
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
          marginBottom: "25px",
          flexWrap: "wrap",
          gap: "15px"
        }}>
          <input
            type="text"
            placeholder="🔍 Search by name or ID..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            style={{
              flex: "1",
              minWidth: "300px",
              padding: "12px 16px",
              border: "1px solid #e2e8f0",
              borderRadius: "8px",
              fontSize: "15px",
              background: "#f8fafc",
              outline: "none"
            }}
          />
          
          <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
            <button
              onClick={handleSelectAll}
              style={{
                padding: "10px 16px",
                background: "#f1f5f9",
                border: "none",
                borderRadius: "8px",
                cursor: "pointer",
                fontWeight: "600",
                color: "#475569"
              }}
            >
              {selectedStudents.length === students.length ? "❌ Deselect All" : "✅ Select All"}
            </button>
            <div style={{
              background: "#4f46e5",
              color: "white",
              padding: "8px 16px",
              borderRadius: "20px",
              fontWeight: "600",
              fontSize: "14px"
            }}>
              Selected: {selectedStudents.length}
            </div>
          </div>
        </div>

        {/* Bulk Actions */}
        <div style={{ display: "flex", gap: "10px", marginBottom: "25px", flexWrap: "wrap" }}>
          <button
            onClick={sendBulkPDFs}
            disabled={selectedStudents.length === 0}
            style={{
              padding: "12px 20px",
              background: selectedStudents.length === 0 ? "#cbd5e1" : "#4f46e5",
              color: "white",
              border: "none",
              borderRadius: "8px",
              cursor: selectedStudents.length > 0 ? "pointer" : "not-allowed",
              fontWeight: "600",
              display: "flex",
              alignItems: "center",
              gap: "8px",
              fontSize: "15px"
            }}
          >
            📱 Send CODE HUB Slips ({selectedStudents.length})
          </button>
          
          <button
            onClick={sendBulkWhatsAppText}
            disabled={selectedStudents.length === 0}
            style={{
              padding: "12px 20px",
              background: selectedStudents.length === 0 ? "#cbd5e1" : "#10b981",
              color: "white",
              border: "none",
              borderRadius: "8px",
              cursor: selectedStudents.length > 0 ? "pointer" : "not-allowed",
              fontWeight: "600",
              display: "flex",
              alignItems: "center",
              gap: "8px",
              fontSize: "15px"
            }}
          >
            💬 Send Texts ({selectedStudents.length})
          </button>

          <button
            onClick={downloadBulkPDFs}
            disabled={selectedStudents.length === 0}
            style={{
              padding: "12px 20px",
              background: selectedStudents.length === 0 ? "#cbd5e1" : "#6b7280",
              color: "white",
              border: "none",
              borderRadius: "8px",
              cursor: selectedStudents.length > 0 ? "pointer" : "not-allowed",
              fontWeight: "600",
              display: "flex",
              alignItems: "center",
              gap: "8px",
              fontSize: "15px"
            }}
          >
            📄 Download Only ({selectedStudents.length})
          </button>
        </div>

        {/* Students Table */}
        <div style={{ overflowX: "auto", borderRadius: "8px", border: "1px solid #e2e8f0" }}>
          <table style={{ width: "100%", borderCollapse: "collapse", minWidth: "800px" }}>
            <thead>
              <tr style={{ background: "#f8fafc" }}>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0" }}>
                  <input
                    type="checkbox"
                    checked={selectedStudents.length === students.length && students.length > 0}
                    onChange={handleSelectAll}
                    style={{ width: "18px", height: "18px", accentColor: "#4f46e5" }}
                    disabled={students.length === 0}
                  />
                </th>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0", fontSize: "14px", fontWeight: "600", color: "#475569" }}>ID</th>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0", fontSize: "14px", fontWeight: "600", color: "#475569" }}>Student Name</th>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0", fontSize: "14px", fontWeight: "600", color: "#475569" }}>Phone</th>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0", fontSize: "14px", fontWeight: "600", color: "#475569" }}>Fee Details</th>
                <th style={{ padding: "16px", textAlign: "left", borderBottom: "2px solid #e2e8f0", fontSize: "14px", fontWeight: "600", color: "#475569" }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {filteredStudents.length > 0 ? (
                filteredStudents.map((student) => {
                  const due = (student.totalFee || 0) - (student.feePaid || 0);
                  const isSelected = selectedStudents.includes(student.studentId);
                  
                  return (
                    <tr key={student.studentId} style={{ 
                      background: isSelected ? "#f0f9ff" : "transparent",
                      borderBottom: "1px solid #f1f5f9"
                    }}>
                      <td style={{ padding: "16px" }}>
                        <input
                          type="checkbox"
                          checked={isSelected}
                          onChange={() => handleSelect(student.studentId)}
                          style={{ width: "18px", height: "18px", accentColor: "#4f46e5" }}
                        />
                      </td>
                      <td style={{ padding: "16px" }}>
                        <strong style={{ color: "#4f46e5" }}>{student.studentId}</strong>
                      </td>
                      <td style={{ padding: "16px" }}>
                        <strong>{student.name}</strong>
                        <div style={{ fontSize: "13px", color: "#64748b", marginTop: "4px" }}>{student.course}</div>
                      </td>
                      <td style={{ padding: "16px" }}>
                        {student.phone ? (
                          <span style={{
                            fontFamily: "'Courier New', monospace",
                            background: "#f1f5f9",
                            padding: "6px 10px",
                            borderRadius: "6px",
                            fontSize: "14px",
                            fontWeight: "600"
                          }}>
                            {student.phone}
                          </span>
                        ) : (
                          <span style={{ color: "#ef4444", fontStyle: "italic" }}>No phone</span>
                        )}
                      </td>
                      <td style={{ padding: "16px" }}>
                        <div style={{ lineHeight: "1.6" }}>
                          <div><strong>Total:</strong> Rs. {student.totalFee || 0}</div>
                          <div><strong style={{ color: "#10b981" }}>Paid:</strong> Rs. {student.feePaid || 0}</div>
                          <div>
                            <strong style={{ color: due === 0 ? "#10b981" : "#ef4444" }}>Due:</strong> 
                            <span style={{ 
                              color: due === 0 ? "#10b981" : "#ef4444",
                              fontWeight: "600",
                              marginLeft: "5px"
                            }}>
                              Rs. {due}
                            </span>
                          </div>
                        </div>
                      </td>
                      <td style={{ padding: "16px" }}>
                        <div style={{ display: "flex", gap: "8px" }}>
                          <button
                            onClick={() => showPDFViewer(student)}
                            style={{
                              padding: "8px 14px",
                              background: "#4f46e5",
                              color: "white",
                              border: "none",
                              borderRadius: "6px",
                              cursor: "pointer",
                              fontSize: "13px",
                              fontWeight: "500",
                              display: "flex",
                              alignItems: "center",
                              gap: "6px"
                            }}
                          >
                            📄 PDF
                          </button>
                          <button
                            onClick={() => {
                              const due = (student.totalFee || 0) - (student.feePaid || 0);
                              const phone = student.phone.replace(/\D/g, '');
                              let formattedPhone = phone;
                              
                              if (phone.length === 10) {
                                formattedPhone = "92" + phone.substring(1);
                              } else if (phone.length === 11 && phone.startsWith("0")) {
                                formattedPhone = "92" + phone.substring(1);
                              }
                              
                              const message = `CODE HUB Fee Payment Slip\n\nDear ${student.name},\n\nYour fee details:\nTotal: Rs. ${student.totalFee || 0}\nPaid: Rs. ${student.feePaid || 0}\nDue: Rs. ${due}\n\nPlease pay the due amount.\n\nCODE HUB Administration`;
                              
                              const whatsappUrl = `https://wa.me/${formattedPhone}?text=${encodeURIComponent(message)}`;
                              window.open(whatsappUrl, '_blank');
                            }}
                            disabled={!student.phone}
                            style={{
                              padding: "8px 14px",
                              background: !student.phone ? "#cbd5e1" : "#10b981",
                              color: "white",
                              border: "none",
                              borderRadius: "6px",
                              cursor: student.phone ? "pointer" : "not-allowed",
                              fontSize: "13px",
                              fontWeight: "500",
                              display: "flex",
                              alignItems: "center",
                              gap: "6px"
                            }}
                          >
                            💬 Text
                          </button>
                        </div>
                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan="6" style={{ padding: "40px", textAlign: "center", color: "#64748b", fontSize: "16px" }}>
                    {searchTerm ? "No students found matching your search" : "No students available"}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* نمونہ سیکشن */}
        <div style={{
          marginTop: "30px",
          padding: "20px",
          background: "#f8fafc",
          borderRadius: "8px",
          border: "1px solid #e2e8f0"
        }}>
          <h4 style={{ margin: "0 0 15px 0", color: "#1e293b", fontSize: "18px", display: "flex", alignItems: "center", gap: "10px" }}>
            ℹ️ How to View Fee Slip
          </h4>
          <div style={{
            background: "white",
            padding: "20px",
            borderRadius: "8px",
            textAlign: "center",
            border: "2px dashed #cbd5e1"
          }}>
            <div style={{ fontSize: "60px", color: "#cbd5e1", marginBottom: "15px" }}>
              📄
            </div>
            <p style={{ margin: "0 0 15px 0", color: "#64748b", fontSize: "16px" }}>
              Click on <strong>"📄 PDF"</strong> button next to any student to view their fee slip
            </p>
            <p style={{ margin: "0", color: "#94a3b8", fontSize: "14px" }}>
              The slip will appear as an overlay with download and send options
            </p>
          </div>
        </div>
      </div>
    </div>
  );
};

export default SendSMS;