'use client';

import { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import {
  BarChart3,
  Download,
  TrendingUp,
  Users,
  Banknote,
  Calendar,
  FileText,
  PieChart,
  Loader2,
  User,
} from 'lucide-react';

const reportTypes = [
  {
    id: 'collection',
    title: 'Fee Collection Report',
    description: 'Monthly/yearly fee collection summary',
    icon: Banknote,
    color: 'bg-emerald-50 text-emerald-600',
  },
  {
    id: 'students',
    title: 'Student List Report',
    description: 'Complete list of students with details',
    icon: Users,
    color: 'bg-blue-50 text-blue-600',
  },
  {
    id: 'attendance',
    title: 'Attendance Report',
    description: 'Monthly attendance summary',
    icon: Calendar,
    color: 'bg-violet-50 text-violet-600',
  },
  {
    id: 'due',
    title: 'Due Fees Report',
    description: 'List of students with pending fees',
    icon: FileText,
    color: 'bg-amber-50 text-amber-600',
  },
  {
    id: 'summary',
    title: 'Course-wise Summary',
    description: 'Student distribution by courses',
    icon: PieChart,
    color: 'bg-pink-50 text-pink-600',
  },
  {
    id: 'revenue',
    title: 'Revenue Analysis',
    description: 'Revenue trends and projections',
    icon: TrendingUp,
    color: 'bg-cyan-50 text-cyan-600',
  },
];

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState(null);
  const [generating, setGenerating] = useState(false);
  const [dateRange, setDateRange] = useState('this-month');
  const [format, setFormat] = useState('pdf');
  const [user, setUser] = useState(null);

  useEffect(() => {
    // Fetch current user for profile info in PDF
    fetch('/api/auth/me')
      .then((res) => res.json())
      .then((data) => setUser(data.user))
      .catch(console.error);
  }, []);

  const generatePDF = async (reportData, reportType) => {
    // Dynamically import jsPDF for client-side only
    const { default: jsPDF } = await import('jspdf');
    const autoTable = (await import('jspdf-autotable')).default;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header with academy info
    doc.setFillColor(79, 70, 229); // Indigo color
    doc.rect(0, 0, pageWidth, 40, 'F');

    // Academy name
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('CH Academy Management', 14, 18);

    // Report title
    doc.setFontSize(14);
    doc.setFont('helvetica', 'normal');
    const reportTitle = reportTypes.find((r) => r.id === reportType)?.title || 'Report';
    doc.text(reportTitle, 14, 30);

    // User profile icon placeholder (top right)
    doc.setFillColor(255, 255, 255);
    doc.circle(pageWidth - 25, 20, 12, 'F');
    doc.setTextColor(79, 70, 229);
    doc.setFontSize(16);
    doc.text(user?.name?.[0]?.toUpperCase() || 'A', pageWidth - 28, 24);

    // Reset text color
    doc.setTextColor(0, 0, 0);

    // Date and generated by info
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    const dateStr = new Date().toLocaleDateString('en-PK', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });
    doc.text(`Generated: ${dateStr}`, 14, 50);
    doc.text(`Generated by: ${user?.name || 'Admin'}`, 14, 56);
    doc.text(
      `Date Range: ${dateRange.replace('-', ' ').replace(/\b\w/g, (l) => l.toUpperCase())}`,
      14,
      62,
    );

    // Reset text color for table
    doc.setTextColor(0, 0, 0);

    // Define table structure based on report type
    let columns = [];
    let rows = [];

    switch (reportType) {
      case 'collection':
        columns = ['Date', 'Student', 'Amount (Rs.)', 'Method', 'Status'];
        rows = reportData.map((item) => [
          new Date(item.date || item.createdAt).toLocaleDateString('en-PK'),
          item.studentName || item.student?.name || 'N/A',
          `Rs. ${item.amount?.toLocaleString() || 0}`,
          item.paymentMethod || 'Cash',
          item.status || 'Paid',
        ]);
        break;

      case 'students':
        columns = ['ID', 'Name', 'Course', 'Phone', 'Status'];
        rows = reportData.map((item) => [
          item.studentId || 'N/A',
          item.name || 'N/A',
          item.course?.name || item.courseName || 'N/A',
          item.phone || 'N/A',
          item.status || 'Active',
        ]);
        break;

      case 'attendance':
        columns = ['Date', 'Student', 'Batch', 'Status'];
        rows = reportData.map((item) => [
          new Date(item.date).toLocaleDateString('en-PK'),
          item.studentName || item.student?.name || 'N/A',
          item.batchName || item.batch?.name || 'N/A',
          item.status || 'Present',
        ]);
        break;

      case 'due':
        columns = ['Student', 'Course', 'Due Amount (Rs.)', 'Due Date', 'Status'];
        rows = reportData.map((item) => [
          item.studentName || item.student?.name || 'N/A',
          item.courseName || item.course?.name || 'N/A',
          `Rs. ${item.dueAmount?.toLocaleString() || item.amount?.toLocaleString() || 0}`,
          item.dueDate ? new Date(item.dueDate).toLocaleDateString('en-PK') : 'N/A',
          item.status || 'Pending',
        ]);
        break;

      case 'summary':
        columns = ['Course', 'Total Students', 'Active', 'Completed', 'Revenue (Rs.)'];
        rows = reportData.map((item) => [
          item.courseName || item.name || 'N/A',
          item.totalStudents || 0,
          item.activeStudents || 0,
          item.completedStudents || 0,
          `Rs. ${item.revenue?.toLocaleString() || 0}`,
        ]);
        break;

      case 'revenue':
        columns = ['Month', 'Collections (Rs.)', 'Expenses (Rs.)', 'Net Revenue (Rs.)'];
        rows = reportData.map((item) => [
          item.month || 'N/A',
          `Rs. ${item.collections?.toLocaleString() || 0}`,
          `Rs. ${item.expenses?.toLocaleString() || 0}`,
          `Rs. ${item.netRevenue?.toLocaleString() || 0}`,
        ]);
        break;

      default:
        columns = ['Data'];
        rows = reportData.map((item) => [JSON.stringify(item)]);
    }

    // Generate table
    autoTable(doc, {
      head: [columns],
      body: rows,
      startY: 70,
      theme: 'striped',
      headStyles: {
        fillColor: [79, 70, 229],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
      },
      alternateRowStyles: {
        fillColor: [245, 245, 250],
      },
      styles: {
        fontSize: 9,
        cellPadding: 4,
      },
    });

    // Footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text(
        `Page ${i} of ${pageCount} | CH Academy Management System`,
        pageWidth / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' },
      );
    }

    // Save PDF
    doc.save(`${reportType}-report-${new Date().toISOString().split('T')[0]}.pdf`);
  };

  const generateReport = async () => {
    if (!selectedReport) return;

    setGenerating(true);
    try {
      const response = await fetch(`/api/reports?type=${selectedReport}&dateRange=${dateRange}`);
      const data = await response.json();

      if (response.ok) {
        if (format === 'pdf') {
          await generatePDF(data.report || [], selectedReport);
        } else {
          // JSON download
          const blob = new Blob([JSON.stringify(data.report, null, 2)], {
            type: 'application/json',
          });
          const url = URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url;
          a.download = `${selectedReport}-report-${new Date().toISOString().split('T')[0]}.json`;
          a.click();
          URL.revokeObjectURL(url);
        }
      } else {
        alert('Error generating report: ' + data.message);
      }
    } catch (error) {
      console.error('Error generating report:', error);
      alert('Error generating report');
    } finally {
      setGenerating(false);
    }
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">Reports</h1>
          <p className="text-muted-foreground">Generate and download various reports</p>
        </div>
      </div>

      <Tabs defaultValue="generate" className="space-y-4">
        <TabsList>
          <TabsTrigger value="generate">Generate Reports</TabsTrigger>
          <TabsTrigger value="history">Report History</TabsTrigger>
        </TabsList>

        <TabsContent value="generate">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {reportTypes.map((report) => {
              const Icon = report.icon;
              return (
                <Card
                  key={report.id}
                  className={`cursor-pointer transition-all hover:shadow-md ${
                    selectedReport === report.id ? 'ring-2 ring-primary' : ''
                  }`}
                  onClick={() => setSelectedReport(report.id)}
                >
                  <CardContent className="p-6">
                    <div className="flex items-start gap-4">
                      <div className={`p-3 rounded-xl ${report.color}`}>
                        <Icon className="h-6 w-6" />
                      </div>
                      <div className="flex-1">
                        <h3 className="font-semibold">{report.title}</h3>
                        <p className="text-sm text-muted-foreground mt-1">{report.description}</p>
                      </div>
                    </div>
                  </CardContent>
                </Card>
              );
            })}
          </div>

          {selectedReport && (
            <Card className="mt-6">
              <CardHeader>
                <CardTitle className="text-lg">Report Options</CardTitle>
                <CardDescription>Configure and generate your report</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <label className="text-sm font-medium">Date Range</label>
                    <select
                      value={dateRange}
                      onChange={(e) => setDateRange(e.target.value)}
                      className="w-full h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"
                    >
                      <option value="this-month">This Month</option>
                      <option value="last-month">Last Month</option>
                      <option value="last-3-months">Last 3 Months</option>
                      <option value="this-year">This Year</option>
                    </select>
                  </div>
                  <div className="space-y-2">
                    <label className="text-sm font-medium">Format</label>
                    <select
                      value={format}
                      onChange={(e) => setFormat(e.target.value)}
                      className="w-full h-10 rounded-md border border-input bg-background px-3 py-2 text-sm"
                    >
                      <option value="pdf">PDF</option>
                      <option value="json">JSON</option>
                    </select>
                  </div>
                </div>
                <div className="flex gap-2">
                  <Button onClick={generateReport} disabled={generating}>
                    {generating ? (
                      <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    ) : (
                      <Download className="mr-2 h-4 w-4" />
                    )}
                    Generate Report
                  </Button>
                  <Button variant="outline" onClick={() => setSelectedReport(null)}>
                    Cancel
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}
        </TabsContent>

        <TabsContent value="history">
          <Card>
            <CardHeader>
              <CardTitle className="text-lg">Recent Reports</CardTitle>
              <CardDescription>Previously generated reports</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {[
                  {
                    name: 'Fee Collection Report - January 2026',
                    date: '2026-02-01',
                    format: 'PDF',
                  },
                  { name: 'Student List Report', date: '2026-01-28', format: 'Excel' },
                  { name: 'Attendance Report - January 2026', date: '2026-01-25', format: 'PDF' },
                ].map((report, index) => (
                  <div
                    key={index}
                    className="flex items-center justify-between p-4 rounded-lg border"
                  >
                    <div className="flex items-center gap-3">
                      <div className="p-2 rounded-lg bg-muted">
                        <FileText className="h-5 w-5 text-muted-foreground" />
                      </div>
                      <div>
                        <p className="font-medium">{report.name}</p>
                        <p className="text-sm text-muted-foreground">
                          {report.date} • {report.format}
                        </p>
                      </div>
                    </div>
                    <Button variant="ghost" size="sm">
                      <Download className="h-4 w-4" />
                    </Button>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>

      {/* Chart Placeholder */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Analytics Overview</CardTitle>
          <CardDescription>Visual representation of key metrics</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="h-64 flex items-center justify-center border-2 border-dashed rounded-lg">
            <div className="text-center text-muted-foreground">
              <BarChart3 className="h-12 w-12 mx-auto mb-3 opacity-50" />
              <p className="font-medium">Charts Coming Soon</p>
              <p className="text-sm">Analytics visualizations will appear here</p>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
